using Application.ApiContracts.File.Responses;
using Application.Common.Models;
using Application.Features.Files.Commands.DeleteFile;
using Application.Features.Files.Commands.RestoreFile;
using Application.Features.Files.Commands.UploadImage;
using FluentAssertions;
using Infrastructure.Authorization.Attribute;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Moq;
using System.Reflection;
using WebAPI.Controllers.V1;
using static Domain.Constants.Permission.PermissionsList;

namespace ControllerTests;

public class MediaFile
{
    private readonly Mock<IMediator> _mediatorMock;
    private readonly MediaFileController _controller;

    public MediaFile()
    {
        _mediatorMock = new Mock<IMediator>();
        _controller = new MediaFileController(_mediatorMock.Object);

        var httpContext = new DefaultHttpContext();
        _controller.ControllerContext = new ControllerContext()
        {
            HttpContext = httpContext
        };
    }

#pragma warning disable CRR0035
    [Fact(DisplayName = "MF_006 - Tải lên ảnh thất bại khi chưa đăng nhập")]
    public void UploadImage_NotAuthenticated_Unauthorized()
    {
        // Arrange
        var method = typeof(MediaFileController).GetMethod("UploadImageAsync");

        // Act
        // Kiểm tra xem controller hoặc method có attribute Authorize không
        var hasAuthorize = method!.GetCustomAttributes(typeof(AuthorizeAttribute), true).Length != 0
                        || typeof(MediaFileController).GetCustomAttributes(typeof(AuthorizeAttribute), true).Length != 0;

        // Assert
        hasAuthorize.Should().BeTrue("API này phải yêu cầu đăng nhập (Authorize)");
    }

    [Fact(DisplayName = "MF_005: UploadImageAsync has RequiresAnyPermissions with Edit/Create permissions")]
    public void UploadImageAsync_HasCorrectPermissionsAttribute()
    {
        var methodInfo = typeof(MediaFileController).GetMethod(nameof(MediaFileController.UploadImageAsync));
        var attribute = methodInfo!.GetCustomAttribute<RequiresAnyPermissionsAttribute>();

        Assert.NotNull(attribute);

        // Assert directly on the Policy string generated by your constructor
        Assert.Contains(Products.Edit, attribute.Policy);
        Assert.Contains(Products.Create, attribute.Policy);
    }

    [Fact(DisplayName = "MF_CT_004: DeleteFileAsync has RequiresAnyPermissions with Edit/Create permissions")]
    public void DeleteFileAsync_HasCorrectPermissionsAttribute()
    {
        var methodInfo = typeof(MediaFileController).GetMethod(nameof(MediaFileController.DeleteFileAsync));
        var attribute = methodInfo!.GetCustomAttribute<RequiresAnyPermissionsAttribute>();

        Assert.NotNull(attribute);

        Assert.Contains(Products.Edit, attribute.Policy);
        Assert.Contains(Products.Create, attribute.Policy);
    }

    [Fact(DisplayName = "MF_012: DeleteFileAsync has RequiresAnyPermissions with Edit/Create permissions")]
    public void DeleteFileAsync_HasCorrectPermissionsAttribute1()
    {
        var methodInfo = typeof(MediaFileController).GetMethod(nameof(MediaFileController.DeleteFileAsync));
        var attribute = methodInfo!.GetCustomAttribute<RequiresAnyPermissionsAttribute>();

        Assert.NotNull(attribute);

        Assert.Contains(Products.Edit, attribute.Policy);
        Assert.Contains(Products.Create, attribute.Policy);
    }

    [Fact(DisplayName = "MF_018: RestoreFileAsync has RequiresAnyPermissions with Edit/Create permissions")]
    public void RestoreFileAsync_HasCorrectPermissionsAttribute()
    {
        var methodInfo = typeof(MediaFileController).GetMethod(nameof(MediaFileController.RestoreFileAsync));
        var attribute = methodInfo?.GetCustomAttribute<RequiresAnyPermissionsAttribute>();

        Assert.NotNull(attribute);

        Assert.Contains(Products.Edit, attribute.Policy);
        Assert.Contains(Products.Create, attribute.Policy);
    }

    [Fact(DisplayName = "MF_CT_002: UploadImageAsync returns BadRequest when file is null")]
    public async Task UploadImageAsync_ReturnsBadRequest_WhenFileIsNull()
    {
        var result = await _controller.UploadImageAsync(null!, CancellationToken.None);

        var statusCodeResult = Assert.IsType<BadRequestResult>(result);
        Assert.Equal(StatusCodes.Status400BadRequest, statusCodeResult.StatusCode);
    }

    [Fact(DisplayName = "MF_CT_003: DeleteFileAsync returns NoContent when mediator succeeds")]
    public async Task DeleteFileAsync_ReturnsNoContent_WhenMediatorSucceeds()
    {
        var storagePath = "test-file.webp";
        _mediatorMock.Setup(m => m.Send(It.IsAny<DeleteFileCommand>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(Result.Success());

        var result = await _controller.DeleteFileAsync(storagePath, CancellationToken.None);

        var statusCodeResult = Assert.IsType<NoContentResult>(result);
        Assert.Equal(StatusCodes.Status204NoContent, statusCodeResult.StatusCode);
    }

    [Fact(DisplayName = "MF_046: DeleteFileAsync returns BadRequest when validation fails")]
    public async Task DeleteFileAsync_ReturnsBadRequest_WhenValidationFails()
    {
        var storagePath = "";
        var validationError = Error.Validation("StoragePath is required", "StoragePath.Empty");

        _mediatorMock.Setup(m => m.Send(It.IsAny<DeleteFileCommand>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(Result.Failure(validationError));

        var result = await _controller.DeleteFileAsync(storagePath, CancellationToken.None);

        // This expects your HandleResult to map Failure -> BadRequest
        var objectResult = Assert.IsType<BadRequestObjectResult>(result);
        Assert.Equal(StatusCodes.Status400BadRequest, objectResult.StatusCode);
    }
#pragma warning restore CRR0035
}
